#!/usr/bin/env python3
import chess
import os
import sys

def clear():
    os.system('cls' if os.name == 'nt' else 'clear')

    def main():
        board = chess.Board()
            history = []
                
                    print("♔ Chess CLI for Termux ♚")
                        print("Moves use UCI format: e2e4  |  Promotion: e7e8q")
                            print("Commands: 'undo', 'quit'\n")
                                input("Press Enter to start...")

                                    while not board.is_game_over():
                                            clear()
                                                    print(board)
                                                            
                                                                    turn = "White" if board.turn else "Black"
                                                                            print(f"\n🔹 Turn: {turn}")
                                                                                    if board.is_check():
                                                                                                print("⚠️  CHECK!")
                                                                                                        if history:
                                                                                                                    print(f"📜 Last move: {history[-1]}")

                                                                                                                            try:
                                                                                                                                        move_input = input("Move > ").strip().lower()
                                                                                                                                                    
                                                                                                                                                                if move_input in ('quit', 'exit'):
                                                                                                                                                                                print("\n👋 Game aborted. Thanks for playing!")
                                                                                                                                                                                                sys.exit(0)
                                                                                                                                                                                                            elif move_input == 'undo' and history:
                                                                                                                                                                                                                            board.pop()
                                                                                                                                                                                                                                            history.pop()
                                                                                                                                                                                                                                                            print("⏪ Undid last move.")
                                                                                                                                                                                                                                                                            input("Press Enter to continue...")
                                                                                                                                                                                                                                                                                            continue
                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                    # Normalize input (remove spaces)
                                                                                                                                                                                                                                                                                                                                move_input = move_input.replace(" ", "")
                                                                                                                                                                                                                                                                                                                                            if len(move_input) < 4 or len(move_input) > 5:
                                                                                                                                                                                                                                                                                                                                                            raise ValueError("Invalid length")
                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                        move = board.parse_uci(move_input)
                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                if not board.is_legal(move):
                                                                                                                                                                                                                                                                                                                                                                                                                                print("❌ Illegal move!")
                                                                                                                                                                                                                                                                                                                                                                                                                                                input("Press Enter to retry...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                continue
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            board.push(move)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        history.append(move_input)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            except ValueError:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("❌ Invalid format. Use: e2e4 or e7e8q (promotion)")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    input("Press Enter to continue...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(f"❌ Error: {e}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    input("Press Enter to continue...")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        clear()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(board)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("\n🏁 Game Over!")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    result = board.result()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if result == "1-0":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("🏆 White wins!")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    elif result == "0-1":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("🏆 Black wins!")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                elif result == "1/2-1/2":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        reason = "Stalemate" if board.is_stalemate() else "Draw"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(f"🤝 {reason}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"📊 Result: {result}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("Thanks for playing!")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            main()